### ISSUE TITLE
Can't upload image to github

### ISSUE THREAD

**Issue by ryanmedeiros** [mding5692/ThinkCapsule-Company-Website#8]
i have this image i want to upload to github so that it can be read by the html file

URL: http://www.anterratech.com/wp-content/uploads/2012/11/Signpost-trans80.png

needs to be named: signpost-test-image.png

**Comment by ryanmedeiros** [comment]
![signpost-test-image](https://cloud.githubusercontent.com/assets/12206490/8174842/c59a3138-13af-11e5-86ea-e954466f2185.png)

**Comment by mding5692** [comment]
See discussion on slack for fixing this issue

**Comment by mding5692** [comment]
http://www.w3schools.com/html/html_images.asp

^See the above for future reference for using images on the internet, thanks
